CREATE SEQUENCE TWEBHOOK_CONFIGURATION_SEQ ;
CREATE SEQUENCE TWEBHOOK_FAILEDREQUEST_SEQ ;

CREATE TABLE TWEBHOOK_CONFIGURATION (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
    CLIENT_SECRET VARCHAR(250) NOT NULL ,
    CLIENT_URL VARCHAR(250) NOT NULL ,
	ENABLE_JOB   char check (ENABLE_JOB in (0,1)),
	ENABLE_CANDIDATE  char check (ENABLE_CANDIDATE in (0,1)),
	ENABLE_COMPANY  char check (ENABLE_COMPANY in (0,1)),
	ENABLE_CONTACT  char check (ENABLE_CONTACT in (0,1)),
	ENABLE_BILLING  char check (ENABLE_BILLING in (0,1)),
	ENABLE_SALARY  char check (ENABLE_SALARY in (0,1)),
    ACTIVE  char check (ACTIVE in (0,1))
 );
 
  
 
CREATE TABLE TWEBHOOK_FAILEDREQUEST (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
	SYNCTYPE VARCHAR(250) NOT NULL ,
	OPERATIONTYPE number(10) NOT NULL,
	DATAID VARCHAR(250) NOT NULL ,
	DATECREATED  DATE DEFAULT NULL,
	INPROGRESS  char check (INPROGRESS in (0,1)) 
 );