CREATE SEQUENCE TWEBHOOK_CONFIGURATION_SEQ ;
CREATE SEQUENCE TWEBHOOK_FAILEDREQUEST_SEQ ;

CREATE TABLE TWEBHOOK_CONFIGURATION (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
    CLIENT_SECRET VARCHAR(250) NOT NULL ,
    CLIENT_URL VARCHAR(250) NOT NULL ,
    ACTIVE  char check (ACTIVE in (0,1)) 
 );
 
CREATE TABLE TWEBHOOK_FAILEDREQUEST (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
	SYNCTYPE VARCHAR(250) NOT NULL ,
	OPERATIONTYPE number(10) NOT NULL,
	DATAID VARCHAR(250) NOT NULL ,
	DATECREATED  DATE DEFAULT NULL,
	INPROGRESS  char check (INPROGRESS in (0,1)) 
 );