CREATE SEQUENCE TWEBHOOK_CONFIGURATION_SEQ ;
CREATE SEQUENCE TWEBHOOK_FAILEDREQUEST_SEQ ;

CREATE TABLE TWEBHOOK_CONFIGURATION (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
    CLIENT_SECRET VARCHAR(250) NOT NULL ,
    CLIENT_URL VARCHAR(250) NOT NULL ,
	ENABLE_JOB   char check (ENABLE_JOB in (0,1)),
	ENABLE_CANDIDATE  char check (ENABLE_CANDIDATE in (0,1)),
	ENABLE_COMPANY  char check (ENABLE_COMPANY in (0,1)),
	ENABLE_CONTACT  char check (ENABLE_CONTACT in (0,1)),
	ENABLE_BILLING  char check (ENABLE_BILLING in (0,1)),
	ENABLE_SALARY  char check (ENABLE_SALARY in (0,1)),
    ACTIVE  char check (ACTIVE in (0,1))
 );
 
  
 
CREATE TABLE TWEBHOOK_FAILEDREQUEST (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
	SYNCTYPE VARCHAR(250) NOT NULL ,
	OPERATIONTYPE number(10) NOT NULL,
	DATAID VARCHAR(250) NOT NULL ,
	DATECREATED  DATE DEFAULT NULL,
	INPROGRESS  char check (INPROGRESS in (0,1)) 
 );
 




CREATE SEQUENCE TWEBHOOK_LOG_SEQ ;

CREATE TABLE TWEBHOOK_LOG (
    ID number(10) NOT NULL,
    TEAMID number(10) NOT NULL,
	SYNCTYPE VARCHAR(250)  DEFAULT NULL,
	OPERATIONTYPE number(10)  DEFAULT NULL,
	DATAID VARCHAR(250)  DEFAULT NULL,
	JSON clob   DEFAULT NULL,
	COUNTER number(10)  DEFAULT NULL,
	EXECTIME number(10)  DEFAULT NULL,
	WHREQUESTTIME number(10)  DEFAULT NULL,
	INPROGRESS  char check (INPROGRESS in (0,1)) , 
	STATUSID   number(10)  DEFAULT NULL,
	ERRORMESSAGE clob   DEFAULT NULL,
	DATECREATED  DATE DEFAULT NULL ,
	DATEUPDATED  DATE DEFAULT NULL 
 );
 
CREATE INDEX TWEBHOOK_LOG_INDEX1 ON TWEBHOOK_LOG (ID, TEAMID);
CREATE INDEX TWEBHOOK_LOG_INDEX2 ON TWEBHOOK_LOG (INPROGRESS, STATUSID);
